### ISSUE TITLE
Fix missing dependencies for frontend layout

### ISSUE THREAD

**Issue by FRickReich** [AhmadAlkhaled/direct_meet#28]
Currently the following packages are not part of the package.json file, and need to be added for the project to run.

- framer-motion
- @uiball/loaders
- axios
- emoji-picker-element
- js-file-download

also nodemon needs to be supplied as dev-dependency for the service to run off-local.

**THIS ISSUE IS OF CRITITAL STATE**

**Comment by Mustaphaibrahim** [comment]
ja das habe ich schon gemerkt dass die nicht in packet-js sind

**Comment by FRickReich** [comment]
ich sehe hier keinen commit der das dem PR hinzugefügt hat, habt ihr aber?

**Comment by Mustaphaibrahim** [comment]
ja
